# Stack Docker Swarm - Mayte Anahi Anchapanta Vinueza
version: '3.8'

services:
  vinueza-app:
    image: ghcr.io/mayte256/vinueza:1.0.5
    ports:
      - "1001:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
    environment:
      - ESTUDIANTE=Mayte Anahi Anchapanta Vinueza
      - APELLIDO=Vinueza

networks:
  traefik-public:
    external: true