version: "3.8"

services:
  vinueza-app:
    image: ghcr.io/mayte256/vinueza:1.0.5
    
    ports:
      - "1004:5000"  # Puerto externo 1004 mapeado al interno 5000
    
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vinueza.entrypoints=http"
        - "traefik.http.routers.vinueza.rule=Host(`vinueza.byronrm.com`)"
        - "traefik.http.middlewares.vinueza-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.vinueza.middlewares=vinueza-https-redirect"
        - "traefik.http.routers.vinueza-secure.entrypoints=https"
        - "traefik.http.routers.vinueza-secure.rule=Host(`vinueza.byronrm.com`)"
        - "traefik.http.routers.vinueza-secure.tls=true"
        - "traefik.http.routers.vinueza-secure.tls.certresolver=letsencrypt"
        - "traefik.http.routers.vinueza-secure.service=vinueza-app"
        - "traefik.http.services.vinueza-app.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
